version: '3.7'
services:

    purplefridaytweetlistener:
        image: purplefridaytweetlistener:latest
        ports:
            - "44398:80"
        volumes:
            - type: bind
              source: /Users/stevelloyd/logs
              target: /app/logs

    web_admin:
        image: purplefriday_wa:latest
        ports: 
            - "8080:80"

networks:
    default:
        external: false
        name: nat
