version: '3.7'
services:

    purplefridaytweetlistener:
        image: purplefridaytweetlistener:latest
        restart: on-failure
        volumes:
            - type: bind
              source: ${HOME}/logs
              target: /app/logs
        links:
            - webadmin
        
        networks:
            - backend

    webadmin:
        image: purplefriday_wa:latest
        restart: on-failure        
        ports: 
            - "80:80"
        volumes:
            - type: bind
              source: ${HOME}/_datastore
              target: /app/_datastore

        networks:
            - backend

networks:
    backend:
        driver: "bridge"
