version: '3.7'
services:

    purplefridaytweetlistener:
        image: purplefridaytweetlistener:latest
        ports:
            - "44398:44398"
        volumes:
            - type: bind
              source: ${HOME}/logs
              target: /app/logs

    web_admin:
        image: purplefriday_wa:latest
        ports: 
            - "80:80"
        volumes:
            - type: bind
              source: ${HOME}/_datastore
              target: /app/_datastore

networks:
    default:
        external: true
        name: nat
