scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - 0.0.0.0:8080
- job_name: grok_exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - 0.0.0.0:9144 
