scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - 127.0.0.1:8080
- job_name: grok_exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - 127.0.0.1:9144 
